import asyncio
import html
import json
import logging

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload

from app.database import get_db
from app.models.project import Project
from app.models.organization import Organization
from app.models.department import Department
from app.models.role import Role
from app.kernel.event_bus import event_bus
from app.kernel.log_handler import set_project_context
from app.workforce.agent_executor import generate_website_files
from app.workforce.file_manager import file_manager

logger = logging.getLogger("studioos.generation")
router = APIRouter(prefix="/api/projects", tags=["generation"])


@router.post("/{project_id}/generate")
async def generate_project(project_id: int, db: Session = Depends(get_db)):
    set_project_context(project_id)
    logger.info(f"Generation started for project #{project_id}")

    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")

    if project.status != "ready":
        raise HTTPException(status_code=400, detail=f"Project status is '{project.status}', expected 'ready'")
    logger.info(f"Project '{project.name}' is ready — loading organization")

    org = db.query(Organization).options(
        joinedload(Organization.departments).joinedload(Department.roles).joinedload(Role.agents)
    ).filter(Organization.project_id == project_id).first()

    if not org:
        raise HTTPException(status_code=404, detail="Organization not found")
    logger.info(f"Organization '{org.name}' loaded — {len(org.departments)} departments")

    try:
        await event_bus.emit_to_project(project_id, "generation_started", {"project_id": project_id})
    except Exception:
        pass

    api_key = project.openai_api_key
    is_demo = api_key and api_key.strip().lower() == "demo"
    if is_demo:
        api_key = None

    departments_data = [
        {"name": d.name, "description": d.description}
        for d in org.departments
    ]
    roles_data = []
    for d in org.departments:
        for r in d.roles:
            roles_data.append({
                "title": r.title,
                "department_name": d.name,
                "responsibilities": r.responsibilities,
            })

    analysis = project.analysis or {}

    if api_key:
        logger.info("Sending request to LLM for website generation...")
        try:
            files = await generate_website_files(
                project_name=project.name,
                project_description=project.description,
                analysis=analysis,
                departments=departments_data,
                roles=roles_data,
                api_key=api_key,
                provider=project.provider or "openai",
                model=project.model or None,
            )
            logger.info(f"LLM returned {len(files)} files")
        except Exception as e:
            logger.error(f"Generation failed for project {project_id}: {e}")
            try:
                await event_bus.emit_to_project(project_id, "generation_error", {"error": str(e)})
            except Exception:
                pass
            raise HTTPException(status_code=500, detail="Website generation failed. Please try again.")
    else:
        logger.info("No API key — using demo template")
        files = [
            {"path": "index.html", "content": _demo_html(project)},
            {"path": "css/style.css", "content": _demo_css()},
            {"path": "js/main.js", "content": _demo_js()},
        ]

    output_dir = await asyncio.to_thread(file_manager.save_website, project_id, files)
    output_url = await asyncio.to_thread(file_manager.get_output_url, project_id)
    logger.info(f"Website saved to {output_dir}")

    try:
        await event_bus.emit_to_project(project_id, "generation_complete", {
            "project_id": project_id,
            "output_url": output_url,
            "files": [f["path"] for f in files],
        })
    except Exception:
        pass

    return {
        "status": "complete",
        "output_url": output_url,
        "files": [{"path": f["path"]} for f in files],
    }


@router.get("/{project_id}/output")
def get_output(project_id: int, db: Session = Depends(get_db)):
    files = file_manager.list_files(project_id)
    return {
        "project_id": project_id,
        "files": files,
    }


def _escape(s: str) -> str:
    return html.escape(s or "", quote=True)


def _demo_html(project: Project) -> str:
    name = _escape(project.name or "StudioOS Project")
    analysis = project.analysis or {}
    summary = _escape(analysis.get("summary", "A project generated by StudioOS."))
    objectives = analysis.get("objectives") or ["Objective 1", "Objective 2", "Objective 3"]
    cards = "\n".join(
        f'<div class="feature-card"><h3>{_escape(o)}</h3></div>'
        for o in objectives[:6]
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{name}</title>
  <link rel="stylesheet" href="css/style.css">
</head>
<body>
  <header>
    <nav>
      <div class="logo">StudioOS</div>
      <ul>
        <li><a href="#about">About</a></li>
        <li><a href="#features">Features</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </nav>
  </header>

  <main>
    <section id="hero">
      <h1>{name}</h1>
      <p>{summary}</p>
      <a href="#features" class="cta">Get Started</a>
    </section>

    <section id="about">
      <h2>About This Project</h2>
      <p>{summary}</p>
    </section>

    <section id="features">
      <h2>Key Objectives</h2>
      <div class="features-grid">
        {cards}
      </div>
    </section>
  </main>

  <footer>
    <p>Generated by StudioOS — Autonomous Organization System</p>
  </footer>
  <script src="js/main.js"></script>
</body>
</html>"""


def _demo_css() -> str:
    return """/* StudioOS Generated Styles */
:root {
  --primary: #2563eb;
  --primary-dark: #1d4ed8;
  --bg: #ffffff;
  --bg-alt: #f8fafc;
  --text: #0f172a;
  --text-muted: #64748b;
  --border: #e2e8f0;
  --radius: 8px;
}

* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: system-ui, -apple-system, sans-serif; color: var(--text); background: var(--bg); line-height: 1.6; }
nav { display: flex; justify-content: space-between; align-items: center; padding: 1rem 2rem; max-width: 1200px; margin: 0 auto; }
nav .logo { font-size: 1.5rem; font-weight: 700; color: var(--primary); }
nav ul { display: flex; gap: 2rem; list-style: none; }
nav a { text-decoration: none; color: var(--text-muted); transition: color 0.2s; }
nav a:hover { color: var(--primary); }
#hero { text-align: center; padding: 6rem 2rem; background: linear-gradient(135deg, var(--bg-alt) 0%, var(--bg) 100%); }
#hero h1 { font-size: 3rem; margin-bottom: 1rem; }
#hero p { font-size: 1.2rem; color: var(--text-muted); max-width: 600px; margin: 0 auto 2rem; }
.cta { display: inline-block; background: var(--primary); color: white; padding: 0.75rem 2rem; border-radius: var(--radius); text-decoration: none; font-weight: 600; transition: background 0.2s; }
.cta:hover { background: var(--primary-dark); }
section { padding: 4rem 2rem; max-width: 1200px; margin: 0 auto; }
section h2 { font-size: 2rem; margin-bottom: 2rem; text-align: center; }
.features-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 1.5rem; }
.feature-card { background: var(--bg-alt); border: 1px solid var(--border); border-radius: var(--radius); padding: 1.5rem; transition: transform 0.2s; }
.feature-card:hover { transform: translateY(-2px); }
footer { text-align: center; padding: 2rem; color: var(--text-muted); border-top: 1px solid var(--border); }"""


def _demo_js() -> str:
    return """// StudioOS Generated Interactions
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('nav a').forEach(function(link) {
    link.addEventListener('click', function(e) {
      e.preventDefault();
      var target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth' });
      }
    });
  });

  var observer = new IntersectionObserver(function(entries) {
    entries.forEach(function(entry) {
      if (entry.isIntersecting) {
        entry.target.style.opacity = '1';
        entry.target.style.transform = 'translateY(0)';
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll('.feature-card').forEach(function(card) {
    card.style.opacity = '0';
    card.style.transform = 'translateY(20px)';
    card.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
    observer.observe(card);
  });
});"""
