import os
import logging
from pathlib import Path

from git import Repo, InvalidGitRepositoryError

logger = logging.getLogger("studioos.git_manager")

REPOS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "repos")


def _get_repo_path(project_id: int) -> str:
    return os.path.join(REPOS_DIR, f"project_{project_id}")


def _get_worktree_path(project_id: int) -> str:
    return os.path.join(_get_repo_path(project_id), "worktree")


def init_repo(project_id: int) -> str:
    path = _get_repo_path(project_id)
    os.makedirs(path, exist_ok=True)
    wt = _get_worktree_path(project_id)
    os.makedirs(wt, exist_ok=True)

    git_path = os.path.join(path, ".git")
    if os.path.exists(git_path):
        return str(path)

    repo = Repo.init(path, bare=False, initial_branch="main")

    readme_path = os.path.join(path, "README.md")
    with open(readme_path, "w") as f:
        f.write(f"# Project {project_id}\n\nAuto-generated by StudioOS\n")

    repo.index.add(["README.md"])
    repo.index.commit("Initial commit")
    logger.info(f"Git repo initialized for project {project_id} at {path}")
    return str(path)


def get_repo(project_id: int) -> Repo:
    path = _get_repo_path(project_id)
    try:
        return Repo(path)
    except InvalidGitRepositoryError:
        raise RuntimeError(f"Git repo not found for project {project_id}. Call init_repo first.")


def get_or_init_repo(project_id: int) -> Repo:
    path = _get_repo_path(project_id)
    if not os.path.exists(os.path.join(path, ".git")):
        init_repo(project_id)
    return get_repo(project_id)


def ensure_agent_branch(project_id: int, agent_name: str) -> str:
    repo = get_or_init_repo(project_id)
    branch_name = f"agent/{agent_name.replace(' ', '_').lower()}"

    try:
        existing = [b.name for b in repo.branches]
        if branch_name in existing:
            return branch_name
    except Exception:
        existing = []

    repo.git.checkout("-b", branch_name)
    repo.git.checkout("main")
    logger.info(f"Created branch {branch_name} for agent {agent_name}")
    return branch_name


def commit_work(project_id: int, agent_name: str, files: dict[str, str], message: str) -> str:
    repo = get_or_init_repo(project_id)
    branch = ensure_agent_branch(project_id, agent_name)

    repo.git.checkout(branch)
    path = _get_repo_path(project_id)

    for filepath, content in files.items():
        full_path = os.path.join(path, filepath)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w") as f:
            f.write(content)
        repo.index.add([filepath])

    commit = repo.index.commit(message)
    repo.git.checkout("main")
    logger.info(f"Agent {agent_name} committed to {branch}: {message}")
    return commit.hexsha


def get_log(project_id: int, max_count: int = 50) -> list[dict]:
    repo = get_or_init_repo(project_id)
    try:
        repo.head.commit
    except ValueError:
        return []
    commits = []
    for c in repo.iter_commits(max_count=max_count):
        branches = []
        try:
            branches = [b.name for b in repo.branches if b.commit.hexsha == c.hexsha]
        except Exception:
            pass
        commits.append({
            "hexsha": c.hexsha,
            "author": str(c.author),
            "message": c.message.strip(),
            "datetime": c.committed_datetime.isoformat(),
            "branches": branches,
        })
    return commits


def get_branches(project_id: int) -> list[dict]:
    repo = get_or_init_repo(project_id)
    try:
        repo.head.commit
    except ValueError:
        return []
    active = repo.active_branch.name
    return [
        {"name": b.name, "commit": b.commit.hexsha, "is_active": b.name == active}
        for b in repo.branches
    ]


def merge_branch(project_id: int, source_branch: str, target_branch: str = "main") -> str:
    repo = get_or_init_repo(project_id)
    repo.git.checkout(target_branch)
    result = repo.git.merge(source_branch)
    logger.info(f"Merged {source_branch} into {target_branch}")
    return result
